version: '3'

services:
  postgres:
    image: postgres:16-alpine3.18
    environment:
      POSTGRES_DB: posttest
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/posttest
      - spring.datasource.username=user
      - spring.datasource.password=password
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - postgres